version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
            cpus: '0.50'
            memory: 1500M

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
