spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: user
    password: password
    data:
      schema: classpath:schema.sql

    hikari:
      maximum-pool-size: 20

    init:
      mode: NEVER



